import { DiagramType, EffortUnit } from "./enums";

/**
 * Authentication settings interface.
 */
export interface IAuthenticationSettings {
    /**
     * Should credentials be cached in local storage?
     */
    cacheCredentials: boolean;

    /**
     * Personal Access Token generated by Azure DevOps used to authenticate requests.
     */
    personalAccessToken: string;

    /**
     * Email address of the Azure DevOps user used to authenticate requests.
     */
    userEmail: string;
}

/**
 * Context settings interface.
 */
export interface IContextSettings {
    /**
     * Identifier of the Azure DevOps Feature work item to be diagramed.
     */
    featureWorkItemId: string;

    /**
     * Name of the Azure DevOps organization the feature to be diagramed is under.
     */
    organizationName: string;

    /**
     * Name of the Azure DevOps organization project the feature to be diagramed is under.
     */
    projectName: string;
}

/**
 * Environment settings interface.
 */
export interface IEnvironmentSettings {
    /**
     * Azure DevOps work item relationship (link) type that identifies the parent work item.
     */
    dependencyRelation: string;

    /**
     * Name of the work item field that contains the estimated amount of time to complete.
     */
    effortField: string;

    /**
     * Unit of measure that the effort field value represents.
     */
    effortFieldUnits: EffortUnit;

    /**
     * Name of the work item field that contains the priority.
     */
    priorityField: string;

    /**
     * Azure DevOps work item tag prefix that identifies the work item's section it is listed under.
     */
    tagSectionPrefix: string;
}

/**
 * User interface settings interface.
 */
export interface IUserInterfaceSettings {
    /**
     * Default effort that is assigned to a work item if one is not provided.
     */
    defaultEffort: number;

    /**
     * Currently selected diagram type.
     */
    diagramType: DiagramType;

    /**
     * Number of resources (people) to be assigned to the feature.
     */
    resourceCount: number;
}

/**
 * Global settings interface.
 */
export interface ISettings {
    /**
     * Global authentication settings.
     */
    authentication: IAuthenticationSettings;

    /**
     * Global context settings.
     */
    context: IContextSettings;

    /**
     * Global environment settings.
     */
    environment: IEnvironmentSettings;

    /**
     * Global user interface settings.
     */
    userInterface: IUserInterfaceSettings;
}

/**
 * Collection of sub-setting interfaces that make up the settings interface.
 */
export type ISubSettings
    = IAuthenticationSettings | IContextSettings | IEnvironmentSettings | IUserInterfaceSettings;